### ISSUE TITLE
RuntimeError: I/O must be done in the executor; Use `await hass.async_add_executor_job()

### ISSUE THREAD

**Issue by jurrianv** [bertbert72/HomeAssistant_Powerlink#5]
I try to use this component but I get the following error:

Logger: homeassistant.components.sensor
Source: util/async_.py:140 
Integration: Sensor (documentation, issues) 
First occurred: 18:46:10 (1 occurrences) 
Last logged: 18:46:10
Error while setting up powerlink2 platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 231, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/powerlink2/sensor.py", line 77, in async_setup_platform
    sensors.append(Powerlink2(config))
  File "/config/custom_components/powerlink2/sensor.py", line 105, in __init__
    self.connect()
  File "/config/custom_components/powerlink2/sensor.py", line 117, in connect
    _LOGGER.info("Powerlink2: login check is " + str(self.do_logincheck()))
  File "/config/custom_components/powerlink2/sensor.py", line 135, in do_logincheck
    r = requests.post(cmd_auto_logout, data=payload, headers=self.getheaders())
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.8/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1263, in _send_request
    self.putrequest(method, url, **skips)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 214, in putrequest
    return _HTTPConnection.putrequest(self, method, url, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 151, in protected_loop_func
    check_loop()
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 140, in check_loop
    raise RuntimeError(
RuntimeError: I/O must be done in the executor; Use `await hass.async_add_executor_job()` at custom_components/powerlink2/sensor.py, line 135: r = requests.post(cmd_auto_logout, data=payload, headers=self.getheaders())

**Comment by jurrianv** [comment]
Some extra info for fixing this?

https://developers.home-assistant.io/docs/asyncio_working_with_async/#calling-sync-functions-from-async
